name: "test"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

          
    - name: n 
      shell: python 
      run: "import json;f=open('package.json');obj=json.load(f); print(obj['keywords']);f.close()"



